### ISSUE TITLE
Discord bot not responding

### ISSUE THREAD

**Issue by danny-h3** [danny-h3/Discord-Weather-Bot#2]
Currently there's an issue where the discord bot does not respond to commands AND messages despite having included all necessary intents. The code that I have in index.js do not seem to have any issues. Some troubleshooting ideas I have: 
- Maybe reset token
- Check bot settings in developer portal
- Review code again for any issues just in case

**Comment by nick-json** [comment]
Double check that on the developer portal the bot has the "MessageContent" privileged enabled
![image](https://github.com/danny-h3/Discord-Weather-Bot/assets/124689027/9f121fc4-14a6-423e-867a-5003c1a173ea)

**Comment by danny-h3** [comment]
The issue turned out to be me not inviting the bot with the proper permissions 💀 Thank you for your response!
